version: "3"

services:

  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/server
    links:
      - db

  db:
    image: "postgres:9"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata